name: Build Haxe Project

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Haxe
        uses: krdlab/setup-haxe@v1
        with:
          haxe-version: 4.2.5

      - name: Install Libraries
        run: |
          haxelib install lime
          haxelib install openfl
          haxelib install flixel
          haxelib install flixel-tools

      - name: Run Lime Setup
        run: |
          haxelib run lime setup

      - name: Build Project
        run: |
          haxelib run lime build windows

      - name: Upload Public Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Strident-Crisis-Shader-generator
          path: export/windows/bin/
